**ASSIGNMENT**

**Experiment 2 : Neural Network from Scratch using Numpy on MNIST dataset**

In [1]:
import tensorflow
from tensorflow import keras

In [2]:
# loading keras mnist dataset
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
y_train.shape

(60000,)

In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
# x_train is in 3D array form, but we need 2D array of x_train ,neural network need x_train in matrix form
# reshape 3D images into 2D vectors
x_train = x_train.reshape(x_train.shape[0], -1)
x_test  = x_test.reshape(x_test.shape[0], -1)

print(x_train.shape)
print(x_test.shape)


(60000, 784)
(10000, 784)


In [8]:
#scaling: using min-max scaling-values scaled to [0,1]
x_train=x_train/255.0
x_test=x_test/255.0

In [9]:
import numpy as np
#initalise weights and bias and learning rate
n=0.01
weights=np.random.rand(784,10)*0.01
bias=np.random.rand(1,10)*0.01
print(weights)
print(bias)

[[0.00623335 0.00998777 0.00354014 ... 0.00523568 0.00842029 0.00991006]
 [0.00250194 0.00771121 0.00977174 ... 0.00574823 0.00291275 0.00883458]
 [0.00305124 0.00340394 0.00769151 ... 0.00481585 0.0043655  0.00602233]
 ...
 [0.00167359 0.00950024 0.00862516 ... 0.00359156 0.00750447 0.0005516 ]
 [0.00606831 0.00902017 0.00161268 ... 0.00970156 0.0003067  0.00249681]
 [0.0039106  0.00800609 0.00887886 ... 0.00916196 0.0069021  0.0029294 ]]
[[0.00031928 0.00086125 0.00142503 0.0001638  0.00345504 0.00737985
  0.00106542 0.00585656 0.00833737 0.00267148]]


In [10]:
#define softmax activation function
def softmax(z):
  z_stable= z - np.max(z) # to avoid overflow exp(1000), subtracting max(z) from all values of z don't change softmax value
  exp_z= np.exp(z_stable)
  return exp_z/np.sum(exp_z)

In [11]:
#define categorical cross entropy

y_train_digit=y_train
y_test_digit=y_test


#convert o/p class to one hot encoding
def one_hot_encode(y, num_classes):
    one_hot = np.zeros((len(y), num_classes))

    for i in range(len(y)):
        one_hot[i][y[i]] = 1

    return one_hot

y_train_digit=one_hot_encode(y_train_digit,10)
y_test_digit=one_hot_encode(y_test_digit,10)




In [12]:
#define loss function
import numpy as np

def categorical_loss(y, y_hat):
    return -np.sum(y * np.log(y_hat + 1e-9)) # avoid log(0)


In [13]:
print(y_train)

[5 0 4 ... 5 6 8]


In [24]:
def Training(x_train, y_train):
    global weights, bias
    epochs = 10

    for epoch in range(epochs):
        total_loss = 0

        for i in range(x_train.shape[0]):
            x = x_train[i:i+1]
            y = y_train[i:i+1]

            # Forward
            z = x @ weights + bias
            y_hat = softmax(z)

            # Loss
            loss = categorical_loss(y, y_hat)
            total_loss += loss   # ✅ FIXED

            # Backward
            dz = y_hat - y
            dw = x.T @ dz
            db = np.sum(dz, axis=0, keepdims=True)

            # Update
            weights -= n * dw
            bias -= n * db

        print(f"Epoch {epoch+1}, Loss: {total_loss / x_train.shape[0]:.4f}")

Training(x_train, y_train)


Epoch 1, Loss: 102.5561
Epoch 2, Loss: 102.5561
Epoch 3, Loss: 102.5561
Epoch 4, Loss: 102.5561
Epoch 5, Loss: 102.5560
Epoch 6, Loss: 102.5560
Epoch 7, Loss: 102.5560
Epoch 8, Loss: 102.5560
Epoch 9, Loss: 102.5560
Epoch 10, Loss: 102.5559


In [25]:
#getting weights and bias
print(weights)
print(bias)

[[0.00623335 0.00998777 0.00354014 ... 0.00523568 0.00842029 0.00991006]
 [0.00250194 0.00771121 0.00977174 ... 0.00574823 0.00291275 0.00883458]
 [0.00305124 0.00340394 0.00769151 ... 0.00481585 0.0043655  0.00602233]
 ...
 [0.00167359 0.00950024 0.00862516 ... 0.00359156 0.00750447 0.0005516 ]
 [0.00606831 0.00902017 0.00161268 ... 0.00970156 0.0003067  0.00249681]
 [0.0039106  0.00800609 0.00887886 ... 0.00916196 0.0069021  0.0029294 ]]
[[135556.92314968 135556.92322175 135556.92216044 135556.92313018
  135556.92372441 135556.92328735 135556.92330703 135556.92317579
  135556.92326547 135556.92311296]]


In [26]:
def prediction(x_test):
    # Ensure 2D shape
    if x_test.ndim == 1:
        x_test = x_test.reshape(1, -1)

    # Forward pass
    z = x_test @ weights + bias
    y_pred = softmax(z)

    # Class prediction
    return np.argmax(y_pred, axis=1)
prediction(x_test)

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
#performance
def accuracy(x, y_true):
    # Predict class labels
    y_pred = prediction(x)

    # Convert one-hot → digit labels (if needed)
    if y_true.ndim == 2:
        y_true = np.argmax(y_true, axis=1)

    # Accuracy calculation
    acc = np.mean(y_pred == y_true)
    return acc


In [28]:
train_acc = accuracy(x_train, y_train)
test_acc  = accuracy(x_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy :", test_acc)


Train Accuracy: 0.0987
Test Accuracy : 0.098
