Tensors Using PyTorch

In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [3]:
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
c = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Tensors Using NumPy

In [5]:
import numpy as np

In [6]:
#1D Tensor
a_np = np.array([1, 2, 3])
print(a_np)

[1 2 3]


In [7]:
#2D Tensor
b_np = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(b_np)

[[1 2 3]
 [4 5 6]]


In [8]:
#3D Tensor
c_np = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c_np)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Basic Elementwise Operation

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a+b)   # addition
print(a-b)   # subtraction
print(a*b)   # multiplication
print(a/b)   # division

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)   # addition
print(a-b)   # subtraction
print(a*b)   # multiplication
print(a/b)   # division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Dot Product

In [11]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [12]:
print(torch.dot(a, b))

tensor(32)


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

np.int64(32)

Matrix Multiplication

In [14]:
#using pytorch
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(a, b))

tensor([[19, 22],
        [43, 50]])


In [15]:
#using numpy
a = np.array([[1, 2],
                  [3, 4]])
b = np.array([[5, 6],
                  [7, 8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

Indexing

In [16]:
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print("Firts Row: ",A[0])
print("Second column:", A[:, 1])
print("Single element:", A[1, 2])

Firts Row:  [10 20 30]
Second column: [20 50 80]
Single element: 60


Slicing

In [17]:
print(A[0:2, 1:3])

[[20 30]
 [50 60]]


Boolean Masking

In [18]:
x = np.array([1, 2, 3, 4, 5, 6])

mask = x > 3
print(mask)
print(x[mask])

[False False False  True  True  True]
[4 5 6]


Extracting SubTensor

In [19]:
B = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9,10], [11,12]]
])

print(B.shape,"\n")

print(B[1],"\n")
print(B[:, 0, :])

(3, 2, 2) 

[[5 6]
 [7 8]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]]


Shape Mnipulation

In [20]:
x = np.array([1, 2, 3, 4, 5, 6])

y = x.reshape(2, 3)
print(y)

[[1 2 3]
 [4 5 6]]


Unsqueeze

In [21]:
x = np.array([1, 2, 3])

print(x.shape)
print(np.expand_dims(x, axis=0).shape)
print(np.expand_dims(x, axis=1).shape)

(3,)
(1, 3)
(3, 1)


Squeeze

In [22]:
z = np.array([[1, 2, 3]])

print(z.shape)
print(np.squeeze(z).shape)

(1, 3)
(3,)


Broadcasting

In [23]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)

[[11 22 33]
 [14 25 36]]


Columnwise broadcasting

In [24]:
c = np.array([[1],
              [2]])

print(A + c)

[[2 3 4]
 [6 7 8]]


Out-of-place

In [25]:
x = np.array([1, 2, 3])
y = x + 10

print(x)
print(y)

[1 2 3]
[11 12 13]


In-place

In [26]:
x = np.array([1, 2, 3])
x += 10

print(x)

[11 12 13]
